import { createContext } from "react";

export const SiteContext = createContext({
	characterName: '',
	characterHP: 100,
	characterMaxHP: 100,
	characterAttackBonus: 0,
	characterEvasionBonus: 0,
	characterDefenseBonus: 0,
	enemyName: '',
	enemyHP: 0,
	enemyMaxHP: 100,
	enemyAttackBonus: 0,
	enemyEvasionBonus: 0,
	enemyDefenseBonus: 0,
	encounterLocation: '',
	encounterAction: '',
	setEncounterLocation: () => { },
	setEncounterAction: () => { },
	setCharacterName: () => { },
	setCharacterHP: () => { },
	setCharacterAttackBonus: () => { },
	setCharacterEvasionBonus: () => { },
	setCharacterDefenseBonus: () => { },
	setEncounterLocation: () => { },
	setEnemyName: () => { },
	setEnemyHP: () => { },
	setEnemyAttackBonus: () => { },
	setEnemyEvasionBonus: () => { },
	setEnemyDefenseBonus: () => { },
});