import { createContext } from "react";

export const SiteContext = createContext({
	characterAttackBonus: 0,
	characterDefenseBonus: 0,
	characterEvasionBonus: 0,
	characterHP: 100,
	characterMaxHP: 100,
	characterName: '',
	defeat: false,
	encounterAction: '',
	encounterLocation: '',
	enemyAttackBonus: 0,
	enemyDefenseBonus: 0,
	enemyEvasionBonus: 0,
	enemyHP: 0,
	enemyMaxHP: 100,
	enemyName: '',
	toggleAutopilot: false,
	victory: false,
	setCharacterAttackBonus: () => { },
	setCharacterDefenseBonus: () => { },
	setCharacterEvasionBonus: () => { },
	setCharacterHP: () => { },
	setCharacterName: () => { },
	setDefeat: () => { },
	setEncounterAction: () => { },
	setEncounterLocation: () => { },
	setEnemyAttackBonus: () => { },
	setEnemyDefenseBonus: () => { },
	setEnemyEvasionBonus: () => { },
	setEnemyHP: () => { },
	setEnemyName: () => { },
	setToggleAutopilot: () => { },
	setVictory: () => { },
});